// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIs.Model;

#nullable disable

namespace WebAPIs.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250531203450_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIs.Model.DCandidate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (100)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (100)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("bloodGroup")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (4)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (10)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("NVARCHAR (100)");

                    b.HasKey("id");

                    b.ToTable("dCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
